# Generated by Django 3.2.6 on 2021-08-28 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descrition', models.TextField(max_length=1000)),
                ('price', models.IntegerField()),
                ('created', models.DateTimeField(default=datetime.datetime(2021, 8, 28, 16, 15, 50, 648898))),
            ],
        ),
    ]
